#!/usr/bin/env python3
"""Build classifier-to-label mapping from tenant SIT exports.

Alternative to the XLSX pipeline for users who don't use testpattern.dev.
Takes a tenant SIT export (from Export-TenantSITs.ps1) and helps create
the classifiers.json that drives DLP rule deployment.

Three modes:

  --init   Generate a mapping CSV template from tenant SITs.
           User fills in the LabelCode column and re-runs with --apply.

  --apply  Read the filled mapping CSV and generate classifiers.json.
           Only rows with a LabelCode value are included.

  --auto   Auto-populate LabelCode using keyword rules, then write the
           pre-filled CSV for user review before --apply.

Usage:
  python scripts/Build-ClassifierSchema.py --init                        # generate mapping CSV
  python scripts/Build-ClassifierSchema.py --init --from-file sits.json  # from custom file
  python scripts/Build-ClassifierSchema.py --auto                        # auto-fill with rules
  python scripts/Build-ClassifierSchema.py --auto --rules my-rules.json  # custom rules
  python scripts/Build-ClassifierSchema.py --apply                       # generate classifiers.json
  python scripts/Build-ClassifierSchema.py --apply --mapping mapping.csv # custom mapping file
"""

import argparse
import csv
import json
import os
import shutil
import sys
from collections import defaultdict
from pathlib import Path

# ---------------------------------------------------------------------------
# Default auto-classification rules
# ---------------------------------------------------------------------------
# Keys are label codes; values are lists of keyword fragments.  A SIT whose
# name contains any of the keywords (case-insensitive) is mapped to that label.
# Rules are evaluated in priority order; the first match wins.

DEFAULT_RULES = {
    "PROT_IT": [
        "credential",
        "password",
        "api key",
        "secret",
        "token",
        "certificate",
        "machine key",
        "connection string",
        "private key",
        "encryption key",
        "signing key",
        "symmetric key",
        "asymmetric key",
        "slack token",
        "github",
        "azure ad",
        "aws",
        "amazon s3",
        "google cloud",
        "storage account",
        "database connection",
        "http auth",
    ],
    "SENS_IT": [
        "source code",
        "configuration file",
        "network diagram",
        "ip address",
        "server name",
    ],
    "SENS_Fin": [
        "bank account",
        "credit card",
        "debit card",
        "tax file",
        "tax identification",
        "iban",
        "swift",
        "financial",
        "routing number",
        "bsb",
        "aba routing",
        "budget",
    ],
    "SENS_Pvca": [
        "passport",
        "driver",
        "social security",
        "national id",
        "birth",
        "health",
        "medical",
        "medicare",
        "insurance",
        "identity card",
        "resident",
        "personal id",
        "social insurance",
        "tax number",
    ],
    "SENS_Gov": [
        "government",
        "clearance",
        "classified",
        "cabinet",
        "minister",
    ],
    "SENS_Law": [
        "law enforcement",
        "police",
        "investigation",
        "warrant",
        "bail",
        "custody",
    ],
    "SENS_Leg": [
        "legal",
        "privilege",
        "litigation",
        "court",
        "contract",
        "subpoena",
    ],
    "OFFI": [
        "address",
        "phone",
        "email",
        "full name",
        "physical address",
        "business number",
        "company number",
    ],
}

# Priority order for rule evaluation (first match wins)
RULE_PRIORITY = [
    "PROT_IT",
    "PROT_Fin",
    "PROT_Pvc",
    "PROT_Gov",
    "PROT_Law",
    "PROT_Leg",
    "SENS_IT",
    "SENS_Fin",
    "SENS_Pvca",
    "SENS_Pvcb",
    "SENS_Gov",
    "SENS_Law",
    "SENS_Leg",
    "OFFI",
]


# ---------------------------------------------------------------------------
# CSV helpers
# ---------------------------------------------------------------------------

CSV_HEADER_COMMENT = """\
# Classifier-to-Label Mapping Template
#
# Generated by Build-ClassifierSchema.py from tenant SIT export.
# Fill in the LabelCode column with the target sensitivity label code,
# then run:  python scripts/Build-ClassifierSchema.py --apply
#
# Valid label codes (from labels.json):
#   {label_codes}
#
# Leave LabelCode blank to exclude a SIT from DLP rules.
# Lines starting with # are ignored when reading.
#
"""

CSV_COLUMNS = ["Name", "Id", "Publisher", "LabelCode"]


def write_csv(path, rows, label_codes=None):
    """Write mapping CSV with UTF-8 BOM (Excel-friendly) and header comment."""
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        # Write header comment
        codes_str = ", ".join(label_codes) if label_codes else "(run with labels.json to see codes)"
        f.write(CSV_HEADER_COMMENT.format(label_codes=codes_str))

        writer = csv.DictWriter(f, fieldnames=CSV_COLUMNS)
        writer.writeheader()

        # Write section separator for Microsoft Built-in
        ms_rows = [r for r in rows if r["Publisher"] == "Microsoft Corporation"]
        custom_rows = [r for r in rows if r["Publisher"] != "Microsoft Corporation"]

        if ms_rows:
            f.write(f"# --- Microsoft Built-in ({len(ms_rows)} SITs) ---\n")
            for row in sorted(ms_rows, key=lambda r: r["Name"]):
                writer.writerow(row)

        if custom_rows:
            f.write(f"# --- Custom ({len(custom_rows)} SITs) ---\n")
            for row in sorted(custom_rows, key=lambda r: r["Name"]):
                writer.writerow(row)

    return len(ms_rows) + len(custom_rows)


def read_csv(path):
    """Read mapping CSV, skipping comment lines."""
    rows = []
    with open(path, "r", newline="", encoding="utf-8-sig") as f:
        # Read all lines, filtering out comments
        lines = []
        for line in f:
            stripped = line.lstrip()
            if stripped.startswith("#"):
                continue
            lines.append(line)

        reader = csv.DictReader(lines)
        for row in reader:
            rows.append(row)
    return rows


# ---------------------------------------------------------------------------
# Data loaders
# ---------------------------------------------------------------------------

def load_tenant_sits(path):
    """Load tenant SIT export (array of {Name, Id, Publisher})."""
    with open(path, "r", encoding="utf-8-sig") as f:
        data = json.load(f)
    if not isinstance(data, list):
        print(f"ERROR: Expected JSON array in {path}", file=sys.stderr)
        sys.exit(1)
    return data


def load_labels(config_dir):
    """Load labels.json and return list of valid label codes."""
    path = os.path.join(config_dir, "labels.json")
    if not os.path.isfile(path):
        print(f"WARNING: labels.json not found at {path}", file=sys.stderr)
        return []
    with open(path, "r", encoding="utf-8") as f:
        labels = json.load(f)
    # Return codes for non-group labels that have a code
    return [
        lbl["code"]
        for lbl in labels
        if lbl.get("code") and not lbl.get("isGroup")
    ]


def load_rules(rules_path):
    """Load auto-classification rules from a JSON file."""
    with open(rules_path, "r", encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Mode 1: --init
# ---------------------------------------------------------------------------

def do_init(args, config_dir):
    """Generate a blank mapping CSV from tenant SITs."""
    sits_path = args.from_file or os.path.join(config_dir, "tenant-sits.json")
    output_path = args.output or os.path.join(config_dir, "classifier-mapping.csv")

    if not os.path.isfile(sits_path):
        print(f"ERROR: SIT file not found: {sits_path}", file=sys.stderr)
        print(f"  Run Export-TenantSITs.ps1 first, or specify --from-file", file=sys.stderr)
        sys.exit(1)

    sits = load_tenant_sits(sits_path)
    label_codes = load_labels(config_dir)

    print(f"  Source:       {sits_path}")
    print(f"  SITs loaded:  {len(sits)}")
    print(f"  Label codes:  {', '.join(label_codes) if label_codes else '(labels.json not found)'}")

    rows = []
    for sit in sits:
        rows.append({
            "Name": sit["Name"],
            "Id": sit["Id"],
            "Publisher": sit["Publisher"],
            "LabelCode": "",
        })

    count = write_csv(output_path, rows, label_codes)
    print(f"\n  Written: {output_path}")
    print(f"  {count} SITs in template")
    print(f"\n  Next step: Open the CSV, fill in LabelCode, then run:")
    print(f"    python scripts/Build-ClassifierSchema.py --apply")


# ---------------------------------------------------------------------------
# Mode 2: --apply
# ---------------------------------------------------------------------------

def do_apply(args, config_dir):
    """Read filled mapping CSV and generate classifiers.json."""
    mapping_path = args.mapping or os.path.join(config_dir, "classifier-mapping.csv")
    output_path = args.output or os.path.join(config_dir, "classifiers.json")

    if not os.path.isfile(mapping_path):
        print(f"ERROR: Mapping file not found: {mapping_path}", file=sys.stderr)
        print(f"  Run with --init first to generate the template.", file=sys.stderr)
        sys.exit(1)

    rows = read_csv(mapping_path)
    label_codes = load_labels(config_dir)

    print(f"  Mapping:      {mapping_path}")
    print(f"  Rows read:    {len(rows)}")

    # Filter to rows with a LabelCode
    mapped = [r for r in rows if r.get("LabelCode", "").strip()]
    unmapped = len(rows) - len(mapped)

    print(f"  Mapped:       {len(mapped)}")
    print(f"  Unmapped:     {unmapped} (skipped)")

    if not mapped:
        print(f"\n  WARNING: No rows have a LabelCode. Nothing to generate.")
        print(f"  Open {mapping_path} and fill in the LabelCode column.")
        sys.exit(0)

    # Validate label codes
    if label_codes:
        invalid = set()
        for r in mapped:
            code = r["LabelCode"].strip()
            if code not in label_codes:
                invalid.add(code)
        if invalid:
            print(f"\n  WARNING: Unknown label codes (not in labels.json):")
            for code in sorted(invalid):
                count = sum(1 for r in mapped if r["LabelCode"].strip() == code)
                print(f"    {code} ({count} SITs)")
            print(f"  Valid codes: {', '.join(label_codes)}")
            print(f"  Continuing anyway -- verify these are intentional.\n")

    # Group by LabelCode
    classifiers = defaultdict(list)
    for r in mapped:
        code = r["LabelCode"].strip()
        entry = {
            "name": r["Name"].strip(),
            "id": r["Id"].strip(),
        }
        classifiers[code].append(entry)

    # Sort entries within each label by name, sort labels alphabetically
    ordered = {}
    for code in sorted(classifiers.keys()):
        ordered[code] = sorted(classifiers[code], key=lambda e: e["name"])

    # Back up existing classifiers.json
    if os.path.isfile(output_path):
        backup_path = output_path + ".bak"
        print(f"  Backing up:   {os.path.basename(output_path)} -> {os.path.basename(backup_path)}")
        shutil.copy2(output_path, backup_path)

    # Write classifiers.json
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(ordered, f, indent=4, ensure_ascii=False)

    # Summary
    total_sits = sum(len(v) for v in ordered.values())
    total_labels = len(ordered)

    print(f"\n  Written: {output_path}")
    print(f"  {total_sits} SITs across {total_labels} labels:\n")

    for code in sorted(ordered.keys()):
        entries = ordered[code]
        print(f"    {code:12s}: {len(entries):4d} SITs")

    print(f"\n  Done. Review classifiers.json, then run deployment scripts.")


# ---------------------------------------------------------------------------
# Mode 3: --auto
# ---------------------------------------------------------------------------

def classify_sit(name, rules):
    """Apply keyword rules to a SIT name and return the matching label code.

    Returns the label code of the first matching rule (by RULE_PRIORITY order),
    or empty string if no rule matches.
    """
    name_lower = name.lower()
    # Evaluate rules in priority order
    for code in RULE_PRIORITY:
        if code not in rules:
            continue
        keywords = rules[code]
        for keyword in keywords:
            if keyword.lower() in name_lower:
                return code
    # Also check any rules not in the priority list (custom rules)
    for code, keywords in rules.items():
        if code in RULE_PRIORITY:
            continue
        for keyword in keywords:
            if keyword.lower() in name_lower:
                return code
    return ""


def do_auto(args, config_dir):
    """Auto-populate LabelCode using keyword rules, then write pre-filled CSV."""
    sits_path = args.from_file or os.path.join(config_dir, "tenant-sits.json")
    output_path = args.output or os.path.join(config_dir, "classifier-mapping.csv")

    if not os.path.isfile(sits_path):
        print(f"ERROR: SIT file not found: {sits_path}", file=sys.stderr)
        print(f"  Run Export-TenantSITs.ps1 first, or specify --from-file", file=sys.stderr)
        sys.exit(1)

    # Load rules
    if args.rules:
        if not os.path.isfile(args.rules):
            print(f"ERROR: Rules file not found: {args.rules}", file=sys.stderr)
            sys.exit(1)
        rules = load_rules(args.rules)
        print(f"  Rules:        {args.rules}")
    else:
        rules = DEFAULT_RULES
        print(f"  Rules:        built-in defaults ({len(rules)} categories)")

    sits = load_tenant_sits(sits_path)
    label_codes = load_labels(config_dir)

    print(f"  Source:       {sits_path}")
    print(f"  SITs loaded:  {len(sits)}")
    print(f"  Label codes:  {', '.join(label_codes) if label_codes else '(labels.json not found)'}")

    # Classify each SIT
    rows = []
    match_counts = defaultdict(int)
    unmatched = 0

    for sit in sits:
        label_code = classify_sit(sit["Name"], rules)
        rows.append({
            "Name": sit["Name"],
            "Id": sit["Id"],
            "Publisher": sit["Publisher"],
            "LabelCode": label_code,
        })
        if label_code:
            match_counts[label_code] += 1
        else:
            unmatched += 1

    count = write_csv(output_path, rows, label_codes)

    # Summary
    total_matched = sum(match_counts.values())
    print(f"\n  Written: {output_path}")
    print(f"  {count} SITs in template")
    print(f"  {total_matched} auto-classified, {unmatched} unmatched\n")

    print(f"  Auto-classification summary:")
    for code in sorted(match_counts.keys()):
        print(f"    {code:12s}: {match_counts[code]:4d} SITs")
    if unmatched:
        print(f"    {'(blank)':12s}: {unmatched:4d} SITs  <- review and assign manually")

    print(f"\n  Next steps:")
    print(f"    1. Open {os.path.basename(output_path)} and review/adjust LabelCode assignments")
    print(f"    2. Fill in any blank LabelCode values for SITs you want in DLP rules")
    print(f"    3. Run:  python scripts/Build-ClassifierSchema.py --apply")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Build classifier-to-label mapping from tenant SIT exports.",
        epilog="Alternative to the XLSX pipeline for users who don't use testpattern.dev.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    mode_group = parser.add_mutually_exclusive_group(required=True)
    mode_group.add_argument(
        "--init",
        action="store_true",
        help="Generate a blank mapping CSV template from tenant SITs",
    )
    mode_group.add_argument(
        "--apply",
        action="store_true",
        help="Read filled mapping CSV and generate classifiers.json",
    )
    mode_group.add_argument(
        "--auto",
        action="store_true",
        help="Auto-populate LabelCode using keyword rules, then write pre-filled CSV",
    )

    parser.add_argument(
        "--from-file",
        metavar="PATH",
        help="Path to tenant SIT JSON file (default: config/tenant-sits.json)",
    )
    parser.add_argument(
        "--mapping",
        metavar="PATH",
        help="Path to mapping CSV file (default: config/classifier-mapping.csv). Used with --apply.",
    )
    parser.add_argument(
        "--rules",
        metavar="PATH",
        help="Path to auto-classification rules JSON (default: built-in). Used with --auto.",
    )
    parser.add_argument(
        "--output",
        metavar="PATH",
        help="Output path (CSV for --init/--auto, JSON for --apply). Defaults to config/.",
    )
    parser.add_argument(
        "--config-dir",
        default="config",
        help="Path to config directory (default: config/)",
    )

    args = parser.parse_args()

    # Resolve paths relative to project root
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent
    config_dir = str((project_root / args.config_dir).resolve())

    print(f"\n  Build-ClassifierSchema.py")
    print(f"  {'='*40}")

    if args.init:
        print(f"  Mode:         init (generate mapping CSV)\n")
        do_init(args, config_dir)
    elif args.apply:
        print(f"  Mode:         apply (generate classifiers.json)\n")
        do_apply(args, config_dir)
    elif args.auto:
        print(f"  Mode:         auto (keyword-based classification)\n")
        do_auto(args, config_dir)

    print()


if __name__ == "__main__":
    main()
